<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.proleap.ibmi</groupId>
		<artifactId>proleap-cobol-ibmi</artifactId>
		<version>1.0.0-ibmi1</version>
	</parent>
	<artifactId>proleap-cobol-api</artifactId>
	<description>ProLeap COBOL API - classes referenced by generated Java code</description>
	<dependencies>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>6.1.4</version>
		</dependency>
	</dependencies>
</project>
