package io.proleap.cobol.runtime;

/**
 * Represents a COBOL SELECT/ASSIGN TO file control entry.
 * Generated by FileControlEntryRule for each SELECT statement
 * in the FILE-CONTROL paragraph.
 *
 * Holds the external file name (from ASSIGN TO) and delegates
 * actual I/O operations to FileControlService.
 */
public class FileControlEntry {

	private final String externalName;
	private String fileStatus = "00";

	public FileControlEntry(final String externalName) {
		this.externalName = externalName;
	}

	/**
	 * Returns the external file name (from ASSIGN TO clause).
	 */
	public String getExternalName() {
		return externalName;
	}

	/**
	 * Returns the current file status (2-character code).
	 */
	public String getFileStatus() {
		return fileStatus;
	}

	/**
	 * Sets the file status (typically updated after I/O operations).
	 */
	public void setFileStatus(final String fileStatus) {
		this.fileStatus = fileStatus;
	}
}
